### ISSUE TITLE
Search results Back button shows search keyboard correctly, but all keyboard focus interaction has stopped

### ISSUE THREAD

**Issue by rosswilson** [bbc/tal-vision#2]
I have come across a bug while developing the Back functionality for a search request that happened to return no matching programmes; an empty search result.

Step 1 shows the keyboard view. Lets enter a query that won't match anything in our programme recordings.
![step 1](https://f.cloud.github.com/assets/1176711/2411705/a5c6d342-aaca-11e3-84e7-4abcc40aeccb.png)

Selecting the Search button correctly transitions us to the search results view, the API request is made and a carousel of programmes is populated. Of course, in this case no programmes were found, so a Back button is shown instead.
![step 2](https://f.cloud.github.com/assets/1176711/2411706/a5c7338c-aaca-11e3-80e3-67d8b1ef492b.png)
![step 3](https://f.cloud.github.com/assets/1176711/2411704/a5c5c416-aaca-11e3-9c79-b30f759055cf.png)

Clicking the back button in Step 3 brings us back to the search keyboard, however, all keyboard interaction has stopped working. No up/down/left/right key navigation is shown. 
![step 4](https://f.cloud.github.com/assets/1176711/2411703/a5c369b4-aaca-11e3-94d7-80e725bf9bf7.png)

I added some debug console.log statements to the global keyhandlers in browserdevice.js which still functioned. I'm calling `parentWidget.back()` in the back button's select handler.

Strangely, on the search results screen, if you select Search from the bottom main navigation the user is returned to the search keyboard view and everything works. Additionally this completely fixes the problem for all further interactions that do use the Back button - until the user refreshes their browser.

Could this be a problem with the history stack? I tried to delve into the Historian class but got lost. Can anybody suggest any ideas?

**Comment by thom4parisot** [comment]
Clicking on _SEARCH_ again triggers a full load of the component itself.

Isn't the `back()` supposed to be executed on the app itself rather than the component?

**Comment by rosswilson** [comment]
According to http://fmtvp.github.io/tal/other/exiting.html the `back()` on the `Application` class is used to exit out of the TAL app completely. The `back()` call on the `parentWidget` works for the video player back button. I just can't see why it works there and not on the search results view.

**Comment by rosswilson** [comment]
I've just found another example of this bug. Play a video from the the search results screen, then press Back within the video view, then play another video from the search results screen, the video plays but all user controls have stopped.

**Comment by thom4parisot** [comment]
So we are either doing something wrong, not hooking the event from the right place, or not calling the back of the proper component.

@jcobbctv is our best hope :-D

**Comment by jcobbctv** [comment]
Hi Tom - I'll get someone to look at this.

**Comment by cisnky** [comment]
Is it an event scoping issue? It's like the event is bubbling to the parent instead of the current target.

**Comment by rosswilson** [comment]
I've been having a play with this again this morning and still haven't come up with a solution. Does anybody have any other suggestions on a fix or a possible direction to look into?

**Comment by rosswilson** [comment]
Have fixed this issue, though with a bit of a hacky fix. I'm now calling the `onDataBound` function a second time after binding the carousel data. This seems to have fixed the issue of focus not being set properly.
